export const mySkills = [
  { title: "HTML", icon: "html", link: "https://developer.mozilla.org/en-US/docs/Web/HTML" },
  { title: "CSS", icon: "css", link: "https://developer.mozilla.org/en-US/docs/Web/CSS" },
  { title: "JavaScript", icon: "javascript", link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" },
  { title: "TypeScript", icon: "typescript", link: "https://www.typescriptlang.org/docs/" },
  { title: "ReactJS", icon: "react", link: "https://react.dev/" },
  { title: "NextJS", icon: "nextjs", link: "https://nextjs.org/docs" },
  { title: "Tailwind CSS", icon: "tailwind", link: "https://tailwindcss.com/docs" },
  { title: "NodeJS", icon: "nodejs", link: "https://nodejs.org/docs/latest/api/" },
  { title: "ExpressJS", icon: "express", link: "https://expressjs.com/" },
  { title: "PHP", icon: "php", link: "https://www.php.net/docs.php" },
  { title: "Laravel", icon: "laravel", link: "https://laravel.com/docs" },
  { title: ".NET", icon: "dotnet", link: "https://learn.microsoft.com/en-us/dotnet/" },
  { title: "Python", icon: "python", link: "https://docs.python.org/3/" },
  { title: "Flutter", icon: "flutter", link: "https://docs.flutter.dev/" },
  { title: "MySQL", icon: "mysql", link: "https://dev.mysql.com/doc/" },
  { title: "PostgreSQL", icon: "postgresql", link: "https://www.postgresql.org/docs/" },
  { title: "MongoDB", icon: "mongodb", link: "https://www.mongodb.com/docs/" },
  { title: "Docker", icon: "docker", link: "https://docs.docker.com/" },
  { title: "GitHub", icon: "gitHub", link: "https://docs.github.com/" },
  { title: "Microsoft Azure", icon: "azure", link: "https://learn.microsoft.com/en-us/azure/" },
  { title: "Git", icon: "git", link: "https://git-scm.com/doc" },
  { title: "Vercel", icon: "vercel", link: "https://vercel.com/docs" },
  { title: "Postman", icon: "postman", link: "https://learning.postman.com/docs/" },
  { title: "Linux", icon: "linux", link: "https://www.kernel.org/doc/html/latest/" },
  { title: "macOS", icon: "macos", link: "https://support.apple.com/macos" },
  { title: "Windows", icon: "windows", link: "https://learn.microsoft.com/en-us/windows/" },
  { title: "pnpm", icon: "pnpm", link: "https://pnpm.io/motivation" },
  { title: "npm", icon: "npm", link: "https://docs.npmjs.com/" },
  { title: "yarn", icon: "yarn", link: "https://yarnpkg.com/getting-started" },
];

export const myContacts = [
  { title: "E-mail", icon: "gmail", link: "https://developer.mozilla.org/en-US/docs/Web/HTML" },
  { title: "Linkedin", icon: "linkedin", link: "https://developer.mozilla.org/en-US/docs/Web/CSS" },
];
